### PR TITLE
fix: app-region height

### PR DESCRIPTION
**Pull request by Keerpich**
the app-region element was extending over the task list dropdown and preventing it from receive click events

### CODE REVIEW

**Comment by Pong420** [comment]
Thanks your PR,
I will take a look later but which OS are you using.

**Comment by Keerpich** [comment]
I'm using Windows 10 Pro

**Comment by Pong420** [comment]
The root cause should be duplicated `.app-region` element. Please check out the latest commit (5097bd73db8f05ec72a8af8525cb805fd9df6922) at master branch. If the issue is fixed I will publish a new version later

**Comment by Keerpich** [comment]
The issue is fixed with that commit. However, linking the size of the app-region with the size of different other elements.

**Comment by Pong420** [comment]
Sorry, I do not well understand your question.
You mean the height of `.app-region` should not equal to the header ?

**Comment by Keerpich** [comment]
I mean `--header-height` is used in multiple places which are not related. 
At the moment you still force .app-region to be 90px tall which should not be the case.
Furthermore, the framework can automatically figure out what the height of `.app-region` should be

**Comment by Pong420** [comment]
The height of `.app-region` is required for frameless mode ( macOS, other OS  could change in `Preferences` )
May be you could overwrite the height to auto here.

https://github.com/Pong420/google-tasks-desktop/blob/5097bd73db8f05ec72a8af8525cb805fd9df6922/src/components/AppRegion/AppRegion.scss#L22-L28

**Pull request closed without merging**
